### ISSUE TITLE
how does SRU work for decoder?

### ISSUE THREAD

**Issue by gary-ren** [taolei87/sru#17]
Would SRU provide any benefits for a decoder that decodes step by step based on the previous decoded output? It will no longer be parallelizable over time steps so the only latency saving would come from the reduced number of operations per time step (compared to LSTM)?

**Comment by taolei87** [comment]
Yes it wouldn't bring much benefit when a trained model is applied in actual decoding / translation.

During training, however, both source and target sequences are known and hence parallelization is still possible (see this [PR](https://github.com/OpenNMT/OpenNMT-py/pull/164) I made to OpenNMT-py) and SRUs do provide the potential to greatly reduce the training time (see section 4.4 of our report).

**Comment by gary-ren** [comment]
Thanks Tao!
