### ISSUE TITLE
python setup.py install   fail

### ISSUE THREAD

**Issue by nsknsl** [taolei87/sru#18]
error:
```
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    version=get_version(),
  File "setup.py", line 21, in get_version
    with open(version_py) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'version.py'
```

**Comment by taolei87** [comment]
hi @ajsyp , this is related to your pr. would you be able to help on this ?  

thanks!

**Comment by benwu232** [comment]
I met same issue. After having a look at the code, I found the 'version.py' in 'sru' sub-directory. Therefore,  a simple modification is :
In setup.py line 20, change
'version.py'  => 'sru/version.py'
then run 'python setup.py install' or 'pip install .'

**Comment by taolei87** [comment]
@benwu232 thanks. I updated the file.
