### ISSUE TITLE
output vs. hidden

### ISSUE THREAD

**Issue by windweller** [taolei87/sru#24]
Hi,

I'm trying to understand what exactly is "output", and what is "hidden".  Based on the code in `cuda_functional.py`, it seems that "output" is corresponding to the hidden states of LSTM, and "hidden" is corresponding to the cell states of LSTM. Is this understanding right?

Or in fact, both hidden and output are the same, hidden is just the last time-step hidden state for each layer, while output is the all-time-step hidden states for the last layer?

```python
output, hidden = rnn(x)      # forward pass

# output is (length, batch size, hidden size * number of directions)
# hidden is (layers, batch size, hidden size * number of directions)

prevx = input
lstc = []
for i, rnn in enumerate(self.rnn_lst):
        h, c = rnn(prevx, c0[i])
        prevx = h
        lstc.append(c)

if return_hidden:
        return prevx, torch.stack(lstc)
else:
        return prevx
```

**Comment by taoleicn** [comment]
hi @windweller 

output is the hidden states h[1..t] of the **last** layer. 
hidden is the concatenation of the **last** state c[t] in **each** layer. 

This is the same as GRU / LSTM in pytorch.

**Comment by windweller** [comment]
I see. Thanks for answering!
