### ISSUE TITLE
Different F1 scores in DrQA when resuming with different batch sizes

### ISSUE THREAD

**Issue by theSage21** [taolei87/sru#26]
Here's a simple test. Train the model for 2 epochs on the SQUAD problem. Here's a bash dump from my machine.

```bash
(venv) ubuntu@x:~/work/sru/DrQA$ python train.py -e 0 -bs 32  --resume checkpoint_epoch_2.pt
seed: 937
10/09/2017 09:36:19 [program starts.]
10/09/2017 09:36:46 [Data loaded.]
10/09/2017 09:36:46 [loading previous model...]
2806118 parameters
10/09/2017 09:37:11 [dev EM: 55.638599810785244 F1: 66.81417432626549]
(venv) ubuntu@x:~/work/sru/DrQA$ python train.py -e 0 -bs 1  --resume checkpoint_epoch_2.pt
seed: 937
10/09/2017 09:37:36 [program starts.]
10/09/2017 09:38:03 [Data loaded.]
10/09/2017 09:38:03 [loading previous model...]
2806118 parameters
10/09/2017 09:39:33 [dev EM: 55.68590350047304 F1: 66.70301086732972]
(venv) ubuntu@ip-172-31-9-81:~/work/sru/DrQA$ python train.py -e 0 -bs 32  --resume checkpoint_epoch_2.pt
seed: 937
10/09/2017 09:42:17 [program starts.]
10/09/2017 09:42:45 [Data loaded.]
10/09/2017 09:42:45 [loading previous model...]
2806118 parameters
10/09/2017 09:43:10 [dev EM: 55.638599810785244 F1: 66.81417432626549]
```

The predictions should not be depending on batch size right? Also what's the point of setting the batch size to 1 in [this](https://github.com/taolei87/sru/blob/master/DrQA/train.py#L168)?

**Comment by taolei87** [comment]
hi @theSage21 

because packed sequence is not supported yet in SRU, each batch may contain a few padding tokens. 

that said, changing the batch size at test time may have a small effect on the model's outputs. thats why you see a small variance when resuming the model.

due to the same reason, i used a batch size of 1 at test time to ensure no padding token is added to the batch.

**Comment by theSage21** [comment]
Thanks. Does it make sense to do that during the reload checks also? During the reload we use batch sizes. If that's ok I can submit a PR.

**Comment by taoleicn** [comment]
of course, any PR / contributions are welcome.
