### ISSUE TITLE
libnvrtc.so: undefined symbol: nvrtcAddNameExpression

### ISSUE THREAD

**Issue by awaelchli** [taolei87/sru#3]
I get the following error message when running the code example you give on the readme page:

![screenshot from 2017-09-11 18-44-35](https://user-images.githubusercontent.com/5495193/30286260-4c761d06-9721-11e7-950c-87e634b3cde3.png)

I'm using Cuda 7.5

Thanks for the help.

**Comment by taolei87** [comment]
hi @awaelchli ,  looks like an error from CUDA. I used CUDA 8. Could you try 8 instead?  

I'll update the requirements if this is the case.

**Comment by yzhang87** [comment]
hi @awaelchli I think nvrtcAddNameExpression is only available for cuda8.

**Comment by awaelchli** [comment]
Yes I will try updating cuda. Thank you!

**Comment by awaelchli** [comment]
@taolei87 @yzhang87 Hi, I can confirm that it only works with cuda 8. Also, the example in the readme file needs to be modified: 1. The input x must be converted to a Variable, 2. cuda() must be called on the model.

**Comment by taolei87** [comment]
@awaelchli  Thank you so much for checking. I'll update the README.
