### ISSUE TITLE
AttributeError when preprocessing data for DrQA

### ISSUE THREAD

**Issue by mojesty** [taolei87/sru#33]
Firstly i ran `download.sh`, and it succesfully downloaded glove and train/dev jsons for SQuAD. However, `python prepro.py` gave me this:
```
Traceback (most recent call last):
  File "prepro.py", line 243, in <module>
    vocab_tag = list(nlp.tagger.tag_names)
AttributeError: 'Tagger' object has no attribute 'tag_names'
```
My Spacy version is `2.0.3`, and it seems like something broke in update from `1.x` that is written in requirements, and I didn't succeed in fixing it myself.
Any suggests?

**Comment by taoleicn** [comment]
Hi,
The `prepro.py` code is taken from https://github.com/hitvoice/DrQA and the author is @hitvoice 
The required spacy version is 1.x according to the README.

@hitvoice any ideas?

**Comment by hitvoice** [comment]
`prepro.py` has been updated a month ago in https://github.com/hitvoice/DrQA. With spacy 2.0, the new script finishes without error, but it takes more than an hour to finish data processing (while with spacy 1.9 it takes only 70 seconds). I'm not able to find out what exactly is the problem and how to accelerate it even after following the "Migrating from spaCy 1.x" guide. 
Related issues in spacy: [#1371](https://github.com/explosion/spaCy/issues/1371) [#1572](https://github.com/explosion/spaCy/issues/1572), which are still open.
I suggest sticking to spacy 1.9 until the spacy development team fixes related performance issues.

**Comment by mojesty** [comment]
Thanks @hitvoice . Do I need to update any other files to make it work with spaCy 2.x? I would like to use the same library version throughout my projects to avoid compatibility problems.

**Comment by hitvoice** [comment]
No, only "prepro.py".

**Comment by aviczhl2** [comment]
@hitvoice when replacing the prepro.py with your new version, a new bug occurs. 

Traceback (most recent call last):
 File "lib/python3.5/site-packages/cupy/cuda/stream.py", line 113, in __del__
   if self.ptr:
AttributeError: 'Stream' object has no attribute 'ptr'
   if self.ptr:
AttributeError: 'Stream' object has no attribute 'ptr'

I'd like to know how to deal with it...

**Comment by mojesty** [comment]
I used @hitvoice 's repo for the DrQa and it worked well, so consider this option also.

**Comment by lenovopast17** [comment]
@aviczhl2 i think you should upgrade your NVIDIA driver, it worked for me.
