### ISSUE TITLE
Error when using DataParallel

### ISSUE THREAD

**Issue by ybzhou** [taolei87/sru#4]
When using with DataParallel, received the following error
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle

single gpu works fine

**Comment by taolei87** [comment]
@ybzhou hi, I've only tested it on single GPU.
the issue might be [here](https://github.com/taolei87/sru/blob/master/cuda_functional.py#L318), where the CUDA steam is created once and fixed when the file is imported. this means it's binded to a single GPU probably. 

need to investigate how to change the stream. let me know if you have a fix :)

**Comment by taolei87** [comment]
- [ ] add multi-GPU support

**Comment by taolei87** [comment]
Now there is a version in "multigpu" branch. I will do more test before merging it into the master branch.  Please feel free to use the current version.
