### ISSUE TITLE
self-normalizing activation

### ISSUE THREAD

**Issue by dpogosov** [taolei87/sru#45]
Hi,

I some people asked you to add recurrent batch norm. There is SELU (self-normalizing ReLU), which is actually easy to implement and works well. Do you mind to add  it?
ref: https://arxiv.org/abs/1706.02515

**Comment by taolei87** [comment]
Sure.  I am working on layer norm, weight norm and better initialization . Let me get back to SELU once I finish it :)

**Comment by taolei87** [comment]
added.
