### ISSUE TITLE
wrong in pytorch=0.4

### ISSUE THREAD

**Issue by yyhlvdl** [taolei87/sru#56]
when I use SRU in pytorch=0.4, wrong as this:
     optimizer.step()
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/sgd.py", line 93, in step
    d_p.add_(weight_decay, p.data)
RuntimeError: The expanded size of the tensor (56) must match the existing size (112) at non-singleton dimension 1
when I repalce SRU to GRU, it won't happen.
I feel sorry that I don't futher study where the wrong happen, but notice it.

**Comment by taoleicn** [comment]
Hi @yyhlvdl 

I will have a major update on the repo soon and it will be 0.4 compatible. Thank you!
