### ISSUE TITLE
ImportError: No module named 'cuda_functional' when running code from Spyder

### ISSUE THREAD

**Issue by RSKothari** [taolei87/sru#79]
```

  File "/usr/local/lib/python3.5/dist-packages/sru/sru_functional.py", line 35, in _lazy_load_cuda_kernel
    from cuda_functional import SRU_Compute_GPU

ImportError: No module named 'cuda_functional'
```
CUDA: 9.1
Torch: 0.4
Python: 3.5

I've tried installing cupy, cupy-90, cupy-91.

 I think the pip install route doesn't automatically append to the PYTHON_PATH variable. This is a problem because while we can edit PYTHON_PATH in the .bashrc file, we would have to explicitly add it using Spyder. This could be a problem if people have multiple PYTHON_PATH variables without using environments.

**Comment by taolei87** [comment]
It seems you installed SRU via `pip install sru`, so I don't understand why you need to set `PYTHONPATH`.

Do you have both `cupy` and `pynvrtc` installed?  and CUDA installed at e.g. `/usr/local/cuda`?

**Comment by RSKothari** [comment]
Yes, I have them all installed in the path mentioned by you. Specifically, CUDA is installed in /usr/local/cuda-9.1, but I changed the CUDA path while installing cupy to this. I should also note that SRU is working fine when running from the terminal, but not from Spyder.

**Comment by RSKothari** [comment]
@taolei87 This is a weird spider issue and path problems. I managed to get SRU up and running but unfortunately I'm getting only NaN values in the output. The network initialization is just fine. I'm trying to debug there issue is coming from.

**Comment by RSKothari** [comment]
@taolei87 I'll open a new issue. This one is considered solved because it's a Spyder, env + path issue.

**Comment by y-research-yu** [comment]
I'd like to say that I got a similar error, and hard-coded the source code as follows, and install from source. It works, I hope I am not misleading.

_SRU_PROG = Program(SRU_CODE, 'sru_prog.cu', lib_name='/opt/cuda/10.0/lib64/libnvrtc.so')  # for pynvrtc >= 9.0
python setup.py install
